// <auto-generated />
namespace DbCalculatorСalorie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserConnectDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserConnectDay));
        
        string IMigrationMetadata.Id
        {
            get { return "202206220648536_UserConnectDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
